export const authTel = 'authTel'
export const authCode = 'authCode'
export const authName = 'authName'
export const main = 'main'
export const history = 'history'
export const payment = 'payment'
export const settings = 'settings'